// Terminbuchung: Kalender, Mehrfachbuchungen pro Zeitslot und Round-Robin-Zuweisung
const DEFAULT_CONFIG = {
    slotDuration: 20, workdayStart: '08:00', workdayEnd: '17:00',
    workdays: [1, 2, 3, 4, 5], roundRobinEnabled: true,
    futureBookingsOnly: true, minDaysAdvance: 0, lastRoundRobinIndex: 0,
    calendarStartDate: '', calendarEndDate: ''
};
let currentWeekStart, selectedDateTime = null, bookedAppointments = [], systemConfig = {};

function readJsonStorage(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key)); return value ?? fallback; } catch { return fallback; } }
function parseLocalDate(value) { const [y, m, d] = value.split('-').map(Number); return new Date(y, m - 1, d); }
function formatDate(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function getAdvisors() { const value = readJsonStorage('advisors', []); return Array.isArray(value) ? value : []; }
function getMonday(date) { const result = new Date(date); const day = result.getDay(); result.setDate(result.getDate() - day + (day === 0 ? -6 : 1)); result.setHours(0, 0, 0, 0); return result; }
function isWithinConfiguredRange(date) { const value = formatDate(date); return (!systemConfig.calendarStartDate || value >= systemConfig.calendarStartDate) && (!systemConfig.calendarEndDate || value <= systemConfig.calendarEndDate); }
function getWeekDays(start) { return Array.from({ length: 5 }, (_, i) => { const date = new Date(start); date.setDate(date.getDate() + i); return date; }); }
function getGermanWeekday(date) { return ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'][date.getDay()]; }
function formatDateRange(start) { const end = new Date(start); end.setDate(end.getDate() + 4); return `${start.toLocaleDateString('de-DE', { day: 'numeric', month: 'long' })} - ${end.toLocaleDateString('de-DE', { day: 'numeric', month: 'long' })}`; }
function isSlotInPast(date, time) { const [h, m] = time.split(':').map(Number); const slot = new Date(date); slot.setHours(h, m, 0, 0); return slot < new Date(); }
function generateTimeSlots() { const slots = [], start = String(systemConfig.workdayStart).split(':').map(Number), end = String(systemConfig.workdayEnd).split(':').map(Number), duration = Number(systemConfig.slotDuration); let current = start[0] * 60 + start[1], endMinutes = end[0] * 60 + end[1]; while (duration > 0 && current < endMinutes) { slots.push(`${String(Math.floor(current / 60)).padStart(2, '0')}:${String(current % 60).padStart(2, '0')}`); current += duration; } return slots; }
function getBookedCount(date, time) { return bookedAppointments.filter(a => a.date === date && a.time === time).length; }
function getRemainingCapacity(date, time) { return Math.max(0, getAdvisors().length - getBookedCount(date, time)); }
function isWeekdayAvailable(date) { return systemConfig.workdays.includes(date.getDay()); }
function setRemainingSlotsText(text = '') { const element = document.getElementById('remainingSlots'); if (element) element.textContent = text; }
function resetSelection() { selectedDateTime = null; const selected = document.getElementById('selectedDateTime'), button = document.getElementById('bookBtn'); if (selected) selected.textContent = 'Noch kein Termin ausgewählt'; setRemainingSlotsText(''); if (button) button.disabled = true; }
function selectDateTime(date, time, element) { document.querySelectorAll('.time-slot.selected').forEach(slot => slot.classList.remove('selected')); element.classList.add('selected'); selectedDateTime = { date, time }; const remaining = getRemainingCapacity(date, time); document.getElementById('selectedDateTime').textContent = `${parseLocalDate(date).toLocaleDateString('de-DE', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} um ${time} Uhr`; setRemainingSlotsText(`${remaining} ${remaining === 1 ? 'Termin ist' : 'Termine sind'} für diesen Zeitslot noch verfügbar.`); document.getElementById('bookBtn').disabled = false; }
function renderCalendar() { const calendar = document.getElementById('calendar'); if (!calendar) return; calendar.innerHTML = ''; getWeekDays(currentWeekStart).forEach(day => { if (!isWeekdayAvailable(day) || !isWithinConfiguredRange(day)) return; const date = formatDate(day), column = document.createElement('div'); column.className = 'day-column'; column.innerHTML = `<div class="day-header"><span class="weekday">${getGermanWeekday(day)}</span><span class="date">${day.getDate()}</span></div><div class="time-slots"></div>`; calendar.appendChild(column); const slots = column.querySelector('.time-slots'); generateTimeSlots().forEach(time => { const remaining = getRemainingCapacity(date, time), unavailable = getAdvisors().length === 0 || remaining === 0 || isSlotInPast(day, time); const element = document.createElement('div'); element.className = `time-slot${unavailable ? ' unavailable' : ''}`; element.textContent = time; if (!unavailable) { element.title = `${remaining} Plätze verfügbar`; element.addEventListener('click', () => selectDateTime(date, time, element)); } slots.appendChild(element); }); }); const display = document.getElementById('weekDisplay'); if (display) display.textContent = formatDateRange(currentWeekStart); }
function assignNextAdvisor() { const advisors = getAdvisors(); if (!advisors.length) return null; const config = { ...DEFAULT_CONFIG, ...readJsonStorage('systemConfig', {}) }, index = Number(config.lastRoundRobinIndex || 0) % advisors.length; config.lastRoundRobinIndex = (index + 1) % advisors.length; localStorage.setItem('systemConfig', JSON.stringify(config)); return advisors[index]; }
function openBookingModal() { if (!selectedDateTime) return; if (getRemainingCapacity(selectedDateTime.date, selectedDateTime.time) <= 0) { alert('Dieser Zeitslot ist inzwischen ausgebucht.'); renderCalendar(); resetSelection(); return; } const date = parseLocalDate(selectedDateTime.date); document.getElementById('confirmText').textContent = `Bestätigen Sie Ihren Termin am ${date.toLocaleDateString('de-DE', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} um ${selectedDateTime.time} Uhr`; document.getElementById('bookingModal').classList.add('active'); }
function confirmBooking() { const name = document.getElementById('nameInput').value.trim(), email = document.getElementById('emailInput').value.trim(); if (!name || !email) { alert('Bitte füllen Sie alle Felder aus.'); return; } if (!selectedDateTime || getRemainingCapacity(selectedDateTime.date, selectedDateTime.time) <= 0) { alert('Dieser Zeitslot ist inzwischen ausgebucht.'); document.getElementById('bookingModal').classList.remove('active'); renderCalendar(); resetSelection(); return; } const advisor = systemConfig.roundRobinEnabled ? assignNextAdvisor() : null; bookedAppointments.push({ id: Date.now(), date: selectedDateTime.date, time: selectedDateTime.time, name, email, advisor, bookedAt: new Date().toISOString() }); localStorage.setItem('bookedAppointments', JSON.stringify(bookedAppointments)); alert(`✅ Termin erfolgreich gebucht!\n\nBestätigung wurde an ${email} gesendet.${advisor ? `\nBerater: ${advisor.name}` : ''}`); document.getElementById('nameInput').value = ''; document.getElementById('emailInput').value = ''; document.getElementById('bookingModal').classList.remove('active'); resetSelection(); renderCalendar(); }
function initialize() { systemConfig = { ...DEFAULT_CONFIG, ...readJsonStorage('systemConfig', {}) }; systemConfig.workdays = Array.isArray(systemConfig.workdays) ? systemConfig.workdays.map(Number) : DEFAULT_CONFIG.workdays; bookedAppointments = readJsonStorage('bookedAppointments', []); if (!Array.isArray(bookedAppointments)) bookedAppointments = []; const configuredStart = systemConfig.calendarStartDate ? parseLocalDate(systemConfig.calendarStartDate) : new Date(); currentWeekStart = getMonday(configuredStart); document.getElementById('prevWeek').addEventListener('click', () => { currentWeekStart.setDate(currentWeekStart.getDate() - 7); resetSelection(); renderCalendar(); }); document.getElementById('nextWeek').addEventListener('click', () => { currentWeekStart.setDate(currentWeekStart.getDate() + 7); resetSelection(); renderCalendar(); }); document.getElementById('bookBtn').addEventListener('click', openBookingModal); document.getElementById('confirmBtn').addEventListener('click', confirmBooking); document.querySelector('.close').addEventListener('click', () => document.getElementById('bookingModal').classList.remove('active')); document.getElementById('bookingModal').addEventListener('click', event => { if (event.target.id === 'bookingModal') event.target.classList.remove('active'); }); renderCalendar(); }
document.addEventListener('DOMContentLoaded', initialize);
